### PR TITLE
Youtube and Vimeo Videos Templates

### PR DESCRIPTION
**Pull request by hydrogen2oxygen**
Links inside a iframe (src) are transformed to "video templates".

Example:
{{< youtube k2NuZhRlWCc >}}

When Hugo discovers this template syntax it will be transformed again in a iframe inside the HTML.

### CODE REVIEW

**Comment by SchumacherFM** [comment]
Thank you for the pull request and sorry I for my late reply.

Can you please:
- Fix the formatting
- Squash all commits into one
- Fix the merge/rebase conflicts.
- Abstract the extract of the youtube and vimeo strings a bit more so that other services can be added easily. Now it's pretty much hard coded.

**Comment by SchumacherFM** [comment]
Please fix at least the merge conflict and then I can merge it.

**Comment by hydrogen2oxygen** [comment]
I will not.

**Comment by chmac** [comment]
@SchumacherFM I’ll see if I can whip up a new PR with the merge conflicts resolved. 👍

**Comment by SchumacherFM** [comment]
@chmac Thanks! That would be awesome!

**Comment by chmac** [comment]
@SchumacherFM I got a bit confused, but I think I've figured it out now. I think two of the commits from this PR have been cherry picked into master already. Now I don't see a merge conflict. Not sure when / how it was fixed, but on GitHub I get "This branch has no conflicts with the base branch" and when I tried a local merge, it worked without conflict.

Wanna merge it now?

**Comment by SchumacherFM** [comment]
@chmac Thanks for investigating. Indeed locally I could merge it without any complains.

**Pull request merged**
